# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-25 14:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20190425_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentOnAnswer',
            fields=[
                ('cmtid', models.AutoField(primary_key=True, serialize=False)),
                ('cmt_desc', models.TextField(blank=True, null=True)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('ansid', models.ForeignKey(blank=True, db_column='ansid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Answer')),
                ('queid', models.ForeignKey(blank=True, db_column='queid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Question')),
                ('userid', models.ForeignKey(blank=True, db_column='userid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'commentonanswer',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='acceptanswer',
            name='createdon',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acceptanswer',
            name='updatedon',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='downvoteanswer',
            name='createdon',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='downvoteanswer',
            name='updatedon',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favouriteanswer',
            name='createdon',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favouriteanswer',
            name='updatedon',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upvoteanswer',
            name='createdon',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upvoteanswer',
            name='updatedon',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
